baseURL = 'https://l10n-bg.dev/'
languageCode = 'bg'
defaultContentLanguage = 'bg'
title = 'Българска локализация на софтуер'

[languages]
  [languages.bg]
    languageName = "Български"
    title = "Българска локализация на софтуер"

    [[languages.bg.menu.main]]
      identifier = "kde"
      name = "KDE"
      url = "/kde/"

    [[languages.bg.menu.main]]
      identifier = "posts"
      name = "Публикации"
      url = "/posts/"

    [[languages.bg.menu.footer]]
      identifier = "kaksepishe"
      name = "Как се пише?"
      url = "https://kaksepishe.com/"

    [[languages.bg.menu.footer]]
      identifier = "bgoffice"
      name = "Проект БГ Сфис"
      url = "https://bgoffice.sourceforge.net/"

    [[languages.bg.menu.footer]]
      identifier = "BgCyrilic"
      name = "Българската кирилица"
      url = "https://cyrillic.bgweb.bg/"
